<p>local AutoIgniteMenu = Menu("AutoIgnite", "Auto Ignite")
AutoIgniteMenu:Boolean("Enabled", "Enabled", true)</p>

<p>local AutoSmiteMenu = Menu("AutoSmite", "Auto Smite")
AutoSmiteMenu:Boolean("Enabled", "Enabled", true)</p>

<p>ChillingSmite = (GetCastName(myHero,SUMMONER_1):lower():find("s5_summonersmiteplayerganker") and SUMMONER_1 or (GetCastName(myHero,SUMMONER_2):lower():find("s5_summonersmiteplayerganker") and SUMMONER_2 or nil))
DuelSmite = (GetCastName(myHero,SUMMONER_1):lower():find("s5_summonersmiteduel") and SUMMONER_1 or (GetCastName(myHero,SUMMONER_2):lower():find("s5_summonersmiteduel") and SUMMONER_2 or nil))</p>

<p>for i,enemy in pairs(GoS:GetEnemyHeroes()) do
      if ChillingSmite and AutoSmiteMenu.Enabled:Value() then
                  if CanUseSpell(myHero, ChillingSmite) == READY and 20+8<em>GetLevel(myHero) &gt; GetCurrentHP(enemy)+GetDmgShield(enemy) and GoS:ValidTarget(enemy, 500) then
                  CastTargetSpell(enemy, ChillingSmite)
                  end
      elseif Ignite and AutoIgniteMenu.Enabled:Value() then
                  if CanUseSpell(myHero, Ignite) == READY and 20</em>GetLevel(myHero)+50 &gt; GetCurrentHP(enemy)+GetDmgShield(enemy)+GetHPRegen(enemy)<em>2.5 and GoS:ValidTarget(enemy, 600) then
                  CastTargetSpell(enemy, Ignite)
                  end
      elseif DuelSmite and AutoSmiteMenu.Enabled:Value() then
                  if CanUseSpell(myHero, DuelSmite) == READY and 54+6</em>GetLevel(myHero) &gt; GetCurrentHP(enemy)+GetDmgShield(enemy)+GetHPRegen(enemy)*3 and GoS:ValidTarget(enemy, 500) then
                  CastTargetSpell(enemy, DuelSmite)
                  end
      end
end</p>

      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/Zentyron/League-of-Legends">League-of-legends</a> is maintained by <a href="https://github.com/Zentyron">Zentyron</a>.</span>

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
      </footer>

    </section>

  
  </body>
</html>
